'use client';
import Link from 'next/link';
import {useState,useEffect} from 'react';
import {Phone,ArrowUpRight,MapPin,Layers,Menu,X,ArrowRight,Clock,Star} from 'lucide-react';
import {business,directions,photos,products} from '@/lib/business';
export function Logo(){return <Link href="/" className="logo" aria-label="Jai Bhavani home"><span className="logomark"><Layers/><b>JB</b></span><span><strong>JAI BHAVANI</strong><small>Plywood & Hardware</small></span></Link>}
export function Actions(){return <div className="actions"><a className="btn" href={'tel:'+business.tel}><Phone size={17}/> Call {business.phone}</a><a className="btn outline" href={directions} target="_blank" rel="noreferrer"><MapPin size={17}/> Get Directions <ArrowUpRight size={16}/></a></div>}
export function Header(){const[open,setOpen]=useState(false);const[compact,setCompact]=useState(false);useEffect(()=>{const fn=()=>setCompact(window.scrollY>40);window.addEventListener('scroll',fn);return()=>window.removeEventListener('scroll',fn)},[]);return <><a className="skip" href="#main">Skip to content</a><div className="announcement"><span><Clock size={13}/> Open Mon–Sat 8 AM–8 PM <i>•</i> Sunday 8 AM–2 PM</span><a href={directions} target="_blank" rel="noreferrer">Get Directions <ArrowUpRight size={13}/></a></div><header className={compact?'compact':''}><div className="header-inner"><Logo/><nav aria-label="Main navigation" className={open?'open':''}>{['Home','Products','About','Gallery','FAQ','Contact'].map(n=><Link onClick={()=>setOpen(false)} href={n==='Home'?'/':'/'+n.toLowerCase()} key={n}>{n}</Link>)}</nav><a className="btn header-call" href={'tel:'+business.tel}><Phone size={16}/> Call Now</a><button className="menu" aria-label={open?'Close menu':'Open menu'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header></>}
export function SectionHeader({eyebrow,title,text,link,href}:{eyebrow?:string,title:string,text?:string,link?:string,href?:string}){return <div className="section-head"><div>{eyebrow&&<div className="eyebrow">{eyebrow}</div>}<h2>{title}</h2>{text&&<p>{text}</p>}</div>{link&&<Link className="text-link" href={href||'/products'}>{link}<ArrowUpRight size={18}/></Link>}</div>}
export function Note({children}:{children:React.ReactNode}){return business.demo?<p className="note"><span>OWNER TO CONFIRM</span>{children}</p>:null}
export function Hero(){return <section className="hero wrap"><div className="hero-copy"><div className="eyebrow"><span/> PLYWOOD & HARDWARE · BADANGPET</div><h1>Plywood & Hardware for Your <em>Next Project</em> in Badangpet</h1><p>From furniture and interiors to renovation requirements, Jai Bhavani Plywood & Hardware gives local customers a convenient place to enquire about plywood and related materials in Badangpet. Call to check what you need before visiting.</p><Actions/><div className="trust-row"><span className="stars">★★★★★</span><strong>{business.rating}</strong><span>Google rating <i>·</i> {business.reviewCount} reviews</span><span className="local"><MapPin size={14}/> Badangpet</span></div></div><figure className="hero-image"><img src={photos[0].src} alt={photos[0].alt} width="720" height="820" fetchPriority="high"/><span className="image-label">THE FOUNDATION OF YOUR NEXT PROJECT</span><figcaption><Layers/><div><strong>Good projects start<br/>with the right materials.</strong><small>Enquire. Confirm. Create.</small></div></figcaption><span className="stock-label">Stock image · illustrative materials</span></figure></section>}
export function ProductCard({product:p,index,detail=false}:{product:typeof products[number],index:number,detail?:boolean}){return <article className="product-card"><div className="product-image"><img src={photos[p.image].src} alt={photos[p.image].alt} width="600" height="460" loading="lazy"/><span>0{index+1}</span></div><div className="product-body"><h3>{p.name}</h3><p>{p.desc}</p><Note>{p.note}</Note>{detail&&<><div className="chips">{p.use.split(' · ').map(x=><span key={x}>{x}</span>)}</div><p className="small">Ask about size, thickness, grade and quantity. Specifications require confirmation.</p></>}<Link className="text-link" href={'/contact?category='+encodeURIComponent(p.name)+'#enquiry'}>Ask About a Product <ArrowUpRight size={17}/></Link></div></article>}
export function ProductSection(){return <section className="wrap section"><SectionHeader eyebrow="MATERIALS, MADE SIMPLE" title="What Are You Looking For?" text="Explore our main product categories and contact us to confirm sizes, specifications, brands and availability." link="Explore Products"/><div className="product-grid">{products.map((p,i)=><ProductCard key={p.name} product={p} index={i}/>)}</div><p className="small image-disclaimer">Category guide · Stock photographs are illustrative and do not show the store’s inventory.</p></section>}
export function Footer(){return <><section className="final-cta"><div className="wrap"><div className="eyebrow">LET’S TALK MATERIALS</div><h2>Have a Material Requirement?<br/>Start With a Quick Call.</h2><p>Tell us what you're looking for and confirm product availability before you visit.</p><Actions/></div></section><footer className="wrap"><div className="footer-grid"><div><Logo/><p>A local plywood supplier in Badangpet. Enquire about materials for furniture, interiors and your next project.</p></div><div><h3>Explore</h3>{['Products','About','Gallery','FAQ','Contact'].map(n=><Link href={'/'+n.toLowerCase()} key={n}>{n}</Link>)}</div><div><h3>Visit the store</h3><p>{business.address}</p><a className="text-link" href={directions}>Get Directions <ArrowUpRight size={16}/></a></div><div><h3>Let’s talk</h3><a href={'tel:'+business.tel}>{business.phone}</a><p>Mon–Sat: 8 AM–8 PM<br/>Sunday: 8 AM–2 PM</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} {business.name}</span><span>Private demo · Temporary wordmark</span><Link href="/contact#privacy">Privacy Policy (pending)</Link></div></footer><div className="mobile-actions"><a href={'tel:'+business.tel}><Phone size={18}/>Call Store</a><a href={directions}><MapPin size={18}/>Directions</a></div></>}
export function Shell({children}:{children:React.ReactNode}){return <><Header/><main id="main">{children}</main><Footer/></>}
